CREATE DATABASE DB_NAME;

CREATE TABLE OPERATIONS_MANAGER
(
    ID      INTEGER NOT NULL,
    MAIL    VARCHAR(200),
    COUNTRY VARCHAR(120),
    STATUS  VARCHAR(200)
);
CREATE TABLE TYPE
(
    ID             INTEGER NOT NULL,
    TYPE           VARCHAR(200),
    BAND           VARCHAR(50),
    COUNTRY        VARCHAR(120),
    RATE           DOUBLE,
    DATE_TO_START  VARCHAR(100),
    DATE_TO_FINISH VARCHAR(100)
);
CREATE TABLE TYPE_OF_EXPENSE
(
    ID   INTEGER NOT NULL,
    TYPE VARCHAR(200)
);
CREATE TABLE ICA
(
    ID               INTEGER NOT NULL,
    ICA_CODE         VARCHAR(120),
    ICA_CORE         VARCHAR(120),
    YEAR             VARCHAR(120),
    ID_PLANNING      VARCHAR(50),
    ICA_OWNER        VARCHAR(150),
    BUDGET           DOUBLE,
    COUNTRY          VARCHAR(120),
    STATUS           VARCHAR(200),
    DEPTO            VARCHAR(50),
    FREQUENCY_BILL   VARCHAR(50),
    CC               VARCHAR(50),
    CITY_NAME_REQ    VARCHAR(100),
    R_CITY_REQ       VARCHAR(50),
    DIVISION         VARCHAR(50),
    MAJOR            VARCHAR(50),
    MINOR            VARCHAR(50),
    LERU             VARCHAR(50),
    DESCRIPTION      VARCHAR(200),
    TYPE             VARCHAR(100),
    NEC              INTEGER,
    TOTAL_PLUS_TAXES DOUBLE,
    START_DATE       DATE,
    END_DATE         DATE,
    CITY_NAME_PERF   VARCHAR(100),
    R_CITY_PERF      VARCHAR(50),
    TOTAL_BILLING    DOUBLE
);
CREATE TABLE ICA_MANAGEMENT
(
    ID     INTEGER NOT NULL,
    MAIL   VARCHAR(150),
    ID_ICA INTEGER,
    ROLE   VARCHAR(200),
    STATUS VARCHAR(120)
);

CREATE TABLE TYPE_EXTRA_HOURS
(
    ID             INTEGER NOT NULL,
    TYPE           VARCHAR(200),
    BAND           VARCHAR(50),
    COUNTRY        VARCHAR(120),
    RATE           DOUBLE,
    DATE_TO_START  VARCHAR(100),
    DATE_TO_FINISH VARCHAR(100)
);